"""baseline schema

Revision ID: 4d54b4171bee
Revises: 
Create Date: 2026-09-01 14:14:49.566317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d54b4171bee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('buyer', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('min_pamuk', sa.Float(), nullable=False),
    sa.Column('max_elastan', sa.Float(), nullable=False),
    sa.Column('ihtiyac_kg', sa.Float(), nullable=False),
    sa.Column('max_fiyat', sa.Float(), nullable=False),
    sa.Column('min_kalite', sa.String(length=2), nullable=False),
    sa.Column('dogrulanmis_ister', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_code'), ['code'], unique=True)

    op.create_table('factory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('factory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factory_name'), ['name'], unique=False)

    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('pamuk', sa.Float(), nullable=False),
    sa.Column('polyester', sa.Float(), nullable=False),
    sa.Column('elastan', sa.Float(), nullable=False),
    sa.Column('kumas', sa.String(length=30), nullable=False),
    sa.Column('gramaj', sa.Integer(), nullable=False),
    sa.Column('en_m', sa.Float(), nullable=False),
    sa.Column('miktar_kg', sa.Float(), nullable=False),
    sa.Column('kalite', sa.String(length=2), nullable=False),
    sa.Column('min_fiyat', sa.Float(), nullable=False),
    sa.Column('depo_gun', sa.Integer(), nullable=False),
    sa.Column('dogrulanmis', sa.Boolean(), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.Column('waste_code', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('inconsistencies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_code'), ['code'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_key'), ['api_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['demand_id'], ['demand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'demand_id', name='uq_match_pair')
    )
    op.create_table('passport_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'seq', name='uq_event_seq')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('agreed_price', sa.Float(), nullable=True),
    sa.Column('agreed_qty_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['demand_id'], ['demand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_code'), ['code'], unique=True)

    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('by_role', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('qty_kg', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('declared', sa.JSON(), nullable=False),
    sa.Column('observed', sa.JSON(), nullable=False),
    sa.Column('mismatch', sa.Boolean(), nullable=False),
    sa.Column('mismatch_fields', sa.JSON(), nullable=True),
    sa.Column('photo_ref', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_verification')
    op.drop_table('bid')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_code'))

    op.drop_table('transaction')
    op.drop_table('passport_event')
    op.drop_table('match')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_api_key'))

    op.drop_table('user')
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_code'))

    op.drop_table('batch')
    with op.batch_alter_table('factory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factory_name'))

    op.drop_table('factory')
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_code'))

    op.drop_table('demand')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
